version: '3.9'

services:
  db:
    image: postgres:latest
    container_name: aad_db_container
    restart: always
    environment:
      POSTGRES_DB: aad_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
